name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Check out submodules
      run: git submodule update --init --recursive
    - name: Build Emgu TF Lite native binary
      run: ./platforms/ubuntu/docker/docker_build_tflite
    - name: Build Emgu TF Lite package
      run: ./platforms/ubuntu/docker/docker_build_emgutf
    - name: Create emgu tf lite artifact folder
      run: mkdir -p emgutf_lite_packages
    - name: Copy zip file to artifact folder
      run: cp b/*.zip emgutf_lite_packages/
    - name: Copy nuget files to artifact folder
      run: cp platforms/nuget/*.nupkg emgutf_lite_packages/
    - uses: actions/upload-artifact@v2
      with:
        path: emgutf_lite_packages

