name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build Emgu TF Lite native binary
      run: ./platforms/ubuntu/docker/docker_build_tflite
    - name: Build Emgu TF Lite package
      run: ./platforms/ubuntu/docker/docker_build_emgutf      

