name: Ubuntu TF Android Builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v2
    - name: Check out submodules
      run: git submodule update --init --recursive
    - name: Build Emgu TF Android native binary
      run: ./build_tf_android arm64 arm64-v8a
      working-directory: ${{ github.workspace }}/platforms/android